### ISSUE TITLE
Abstract Store

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/linked-data-repository#17]
We don't really want to be calling the database(s) directly from the handlers, we want things to be more decoupled than that.

Sketch out an `abc` `Store` class to hang all the data/database interacting methods required by the endpoints on. Implement stubbed driver(s) with tests.

- [ ] Abstract Store Class(es).
- [ ] Stubbed implementation
- [ ] Store Tests that will run with the stubbed (and later) drivers.

This could benefit from the result of: https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/linked-data-repository/15

**Comment by roblinksdata** [comment]
Now duplicated with more specific tasks to set up the shared library.
