### ISSUE TITLE
Decide on & Set up Message Queueing Service

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/linked-data-repository#28]
Do we want:

- GCP pub/sub
  - can we run this locally to aid our developement processed?
- RabbitMQ/Kafka inside k8s?

Make sure it's set up with topics for:

* processing uploaded CSV-W/RDF artifacts

-------------------

We're going to go with the GCP pub/sub service for now until told otherwise by the techboard.

At this point we should see if we can deploy & configure GCP pub/sub with helm, if not we need to bring terraform in here and see whether it can play nicely with helm. Ideally we want to be in the situation where we can deploy the entire infrastructure with one or two commands to helm and/or terraform. 

- We need a specific queues for:
  - [ ] the integration test enviornment.
  - [ ] An instance for local development on developer's computer / instructions on how a developer can set up a queue for themselves to test with independently. 

- [ ] If it's available, enable the `exactly once` delivery option so we don't duplicate processing for the same queue item.

**Comment by canwaf** [comment]
Decided on using Google Pub/Sub.

**Comment by scheung38** [comment]
Are we using one-to-many, many-to-one or many-to-many topology?

Also, we have reviewed the pricing on it:

US$29,640 for 100MiBps, 2 Number of subscriptions
 
![Screenshot 2022-02-14 at 00.23.34.png](https://images.zenhubusercontent.com/6188f98d846b696ca8069573/485bea68-870a-4f59-ad71-796381f82fb2)

Did proposed Redpanda from Vectorize.io: C++ under the hood, 100% Kafka API backward compatible (No resource hungry JVM / Java to fine tune to get good performance. PubSub is also based on Kafka under the hood. i.e more Java

![Screenshot 2022-02-14 at 00.37.27.png](https://images.zenhubusercontent.com/6188f98d846b696ca8069573/cf50dd6c-e1e4-4a01-9b9c-108d36936834)

https://whoisnnamdi.com/why-developers-love-redpanda/

**Comment by scheung38** [comment]
![Screenshot 2022-02-14 at 00.23.34.png](https://images.zenhubusercontent.com/6188f98d846b696ca8069573/485bea68-870a-4f59-ad71-796381f82fb2)

**Comment by roblinksdata** [comment]
> 

@SyedZulfikarAH does this concur with the pricing as you understood it? I understood it wasn't likely to cost us anything for the first 10GB of data.

**Comment by SyedZulfikarAH** [comment]
The Google Pub-Sub pricing is based on the below criteria

1. Throughput costs - The first 10 GiB of throughput per month is free. After that, the price is $40 per TiB
2. Storage costs - $0.27 per GiB-month
3. Egress costs - There are no zone egress fees for Pub/Sub usage.
4. Cross-project Pub/Sub billing - If Pub/Sub is used across projects, Pub/Sub fees are billed to the project that contains the requested resource
5. Filtered messages costs -  No egress fees for filtered messages but incur throughput fees for the messages that don't match a filter

<img width="1424" alt="gcppubsub-pricingestimate" src="https://user-images.githubusercontent.com/36515121/153870985-c6a75d20-8551-4bee-9cc0-a0865230f68f.png">

Note: The screenshot is only estimate, the actual cost may vary. The criteria given are 1 topic, 50mb volume of bytes per day, 5 subscriptions, 7 day retention, retained acknowledged backlog 5, retention 7 days, Snapshots 30 per month and retention 7 days. Waiting for the Google sales team to confirm on the pub/sub pricing example given on their website.
