### ISSUE TITLE
Setup Buckets

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/linked-data-repository#29]
* One (slowish) bucket for uploaded artifacts (read-write many) -- 1-2 GB for now
* One fast-read bucket for processed artifacts (read-write many) -- 5 GB for now

Make sure they're mounted inside the k8s containers we're running our service on.

This may be one for Seb inside the k8s config files.

- [ ] Need to be able to scale these up as required.
- [ ] Can we see the costs per GB for the different speed solutions.
- [ ] Cost comparison betwen GCP's own bucket solution & the minio solution.

**Comment by scheung38** [comment]
https://console.cloud.google.com/storage/browser/gsscogs-linkeddata-public
gs://gsscogs-linkeddata-public
Public access status - Was Not public -> Public to Internet


https://console.cloud.google.com/storage/browser/gsscogs-linkeddata-private
gs://gsscogs-linkeddata-private
Public access status - Not public

**Comment by roblinksdata** [comment]
@scheung38 I don't think we want anything publicly accessible since some of the resources will need to be protected behind access restrictions.

**Comment by scheung38** [comment]
Thanks @robons, don't think Google has concept of slow or fast, speed is the same, rather they refer to frequency of access: hot or cold and hence pricing. If we use colder mode pay less for storage but more for access

**Comment by scheung38** [comment]
This is just estimate, taking a rough estimate:

https://cloud.google.com/products/calculator#id=dee528e0-588b-4e33-8091-b9bb383433bf
